list=["Do", "Re", "Mi", "Fa", "So", "La", "Ti"]
list.clear()
list.insert(1, "Mi")
list.insert(2, "Do")
list.insert(3, "Fa")
list.insert(4, "So")
list.insert(5, "La")
list.insert(6, "Ti")
list.insert(7, "Re")
print(list)